28-04-2022 14:52:19 INFO     TRANSIT_STARTED_FROM_PLATE	['ZM970EO']	FROM FRONT_CAM
28-04-2022 14:52:19 INFO     TRANSIT_STARTED_FROM_BADGE	['02328d06-c6f2-11ec-8ffc-e4b31807c5aa']	RFID
28-04-2022 14:52:19 INFO     ACCESS_GRANTED TO [plate,badge]

28-04-2022 14:52:19 INFO     ACCESS_REFUSED TO [plate,badge]
28-04-2022 14:52:19 INFO     TRANSIT_ENDED 

28-04-2022 14:52:19 INFO     manual_open_gate
28-04-2022 15:21:25 ERROR    Task exception was never retrieved
future: <Task finished name='Task-7' coro=<TransitAnalyzer.createObservable.<locals>.on_subscription.<locals>.log() done, defined at C:\Users\UTENTE\Documents\python\reactive\Controllo_Accessi\lane_analyzer.py:24> exception=AttributeError("'Logger' object has no attribute 'is_stopped'")>
Traceback (most recent call last):
  File "C:\Users\UTENTE\Documents\python\reactive\Controllo_Accessi\lane_analyzer.py", line 33, in log
    observer.on_next(self.logObject)
  File "C:\Users\UTENTE\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\reactivex\observer\autodetachobserver.py", line 28, in on_next
    self._on_next(value)
  File "C:\Users\UTENTE\Documents\python\reactive\Controllo_Accessi\logger.py", line 39, in on_next
    logging.info(self.formatEvent(evento))
TypeError: Logger.formatEvent() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\UTENTE\Documents\python\reactive\Controllo_Accessi\lane_analyzer.py", line 35, in log
    observer.on_error(err)
  File "C:\Users\UTENTE\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\reactivex\observer\autodetachobserver.py", line 36, in on_error
    self._on_error(error)
  File "C:\Users\UTENTE\Documents\python\reactive\Controllo_Accessi\logger.py", line 46, in on_error
    return super().on_error(error)
  File "C:\Users\UTENTE\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\reactivex\observer\observer.py", line 54, in on_error
    if not self.is_stopped:
AttributeError: 'Logger' object has no attribute 'is_stopped'
28-04-2022 15:22:30 INFO     TRANSIT_STARTED_FROM_PLATE	LQ147BP	 READ BYFRONT_CAM
28-04-2022 15:22:31 INFO     TRANSIT_STARTED_FROM_BADGE	3929ffa4-c6f6-11ec-aad2-e4b31807c5aa	 READ BYRFID
28-04-2022 15:22:32 INFO     TRANSIT_STARTED_FROM_PLATE	RR867EO	 READ BYREAR_CAM
28-04-2022 15:22:32 INFO     ACCESS_GRANTED TO	RR867EO,None
28-04-2022 15:22:41 INFO     TRANSIT_STARTED_FROM_PLATE	NN500RZ	 READ BYFRONT_CAM
28-04-2022 15:22:45 INFO     TRANSIT_STARTED_FROM_PLATE	LC060KY	 READ BYREAR_CAM
28-04-2022 15:22:47 INFO     TRANSIT_STARTED_FROM_BADGE	3928cd3d-c6f6-11ec-8864-e4b31807c5aa	 READ BYRFID
